language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements-build.txt
# command to run tests
script:
  - python3 .manage_django.py collectstatic --noinput
  - python3 .manage_django.py test